#pragma once
#include <inc.hpp>
namespace games
{
	namespace eft
	{
        enum Bones : uint32_t
        {
            HumanHead = 133,

            HumanNeck = 132,
            HumanSpine3 = 37,
            HumanSpine2 = 36,
            HumanSpine1 = 29,
            HumanPelvis = 14,

            HumanLCalf = 17,
            HumanLFoot = 18,

            HumanRCalf = 22,
            HumanRFoot = 23,

            HumanLForearm2 = 93,
            HumanLElbow = 92,
            HumanLUpperarm = 91,

            HumanRForearm2 = 114,
            HumanRElbow = 113,
            HumanRUpperarm = 112,
        };

        /*
        22a42fa5f90 : EFT.Player
			static fields
				0 : \uE0A9 (type: EFT.Player.)
			fields
				18 : \uE000 (type: System.Action<System.Single,System.Single,System.Int32>)
				20 : \uE001 (type: System.Action<EFT.InventoryLogic.SightComponent>)
				28 : _characterController (type: \uE20E)
				30 : _triggerColliderSearcher (type: TriggerColliderSearcher)
				540 : \uE002 (type: System.Boolean)
				38 : \uE003 (type: EFT.Interactive.WorldInteractiveObject)
				40 : \uE004 (type: \uE4FE)
				544 : \uE005 (type: System.Single)
				548 : \uE006 (type: System.Single)
				54c : \uE007 (type: System.Boolean)
				54d : \uE008 (type: System.Boolean)
				48 : Pedometer (type: \uE4CC)
				550 : HeadRotation (type: UnityEngine.Vector3)
				55c : _mouseSensitivityModifier (type: System.Single)
				50 : _mouseSensitivityModifiers (type: System.Collections.Generic.Dictionary<EFT.Player.EMouseSensitivityModifier,System.Single>)
				560 : \uE009 (type: UnityEngine.Vector2)
				568 : \uE00A (type: UnityEngine.Vector2)
				570 : TrunkRotationLimit (type: System.Single)
				574 : \uE00B (type: System.Single)
				578 : PoseMemo (type: System.Single)
				57c : \uE00C (type: System.Boolean)
				580 : LeanLock (type: System.Single)
				584 : \uE00D (type: System.Single)
				588 : \uE00E (type: System.Single)
				58c : _prevHeight (type: System.Single)
				590 : HeightSmoothTime (type: System.Single)
				594 : \uE00F (type: System.Single)
				598 : \uE010 (type: System.Single)
				59c : \uE011 (type: System.Single)
				58 : \uE013 (type: EFT.Player.)
				60 : LeftHandInteractionTarget (type: GripPose)
				68 : Grounder (type: RootMotion.FinalIK.GrounderFBBIK)
				70 : HitReaction (type: RootMotion.FinalIK.HitReaction)
				5a0 : RibcageScaleCurrent (type: System.Single)
				5a4 : RibcageScaleCurrentTarget (type: System.Single)
				78 : _elbowBends (type: UnityEngine.Transform[])
				80 : HandPosers (type: HandPoser[])
				5a8 : UtilityLayerRange (type: UnityEngine.Vector2)
				5b0 : UtilityLayerLerpSpeed (type: System.Single)
				88 : LMarkerRawBlender (type: EFT.Player.ValueBlender)
				90 : LayerWeight (type: EFT.Player.ValueBlender)
				98 : ThirdIkWeight (type: EFT.Player.BetterValueBlender)
				5b4 : GripAutoAdjust (type: System.Boolean)
				a0 : _fbbik (type: RootMotion.FinalIK.FullBodyBipedIK)
				a8 : _playerBody (type: EFT.PlayerBody)
				5b8 : ThirdPersonWeaponRootAuthority (type: System.Single)
				5bc : \uE014 (type: System.Single)
				5c0 : \uE015 (type: System.Single)
				5c4 : \uE016 (type: System.Single)
				5c8 : \uE017 (type: System.Single)
				5cc : \uE018 (type: System.Single)
				5d0 : \uE019 (type: System.Single)
				5d4 : \uE01A (type: System.Single)
				5d8 : \uE01B (type: System.Single)
				5dc : \uE01C (type: System.Single)
				5e0 : \uE01D (type: System.Single)
				5e4 : \uE01E (type: System.Single)
				5e8 : \uE01F (type: System.Single)
				5ec : \uE020 (type: System.Boolean)
				5ed : \uE021 (type: System.Boolean)
				5ee : \uE022 (type: System.Boolean)
				5ef : \uE023 (type: System.Boolean)
				5f0 : \uE024 (type: System.Boolean)
				5f1 : \uE025 (type: System.Boolean)
				b0 : \uE026 (type: UnityEngine.Vector3[])
				5f4 : \uE027 (type: UnityEngine.Vector3)
				600 : \uE028 (type: UnityEngine.Vector3)
				60c : \uE029 (type: UnityEngine.Vector3)
				618 : \uE02A (type: UnityEngine.Vector3)
				624 : \uE02B (type: UnityEngine.Vector3)
				630 : \uE02C (type: UnityEngine.Quaternion)
				640 : \uE02D (type: UnityEngine.Quaternion)
				650 : \uE02E (type: UnityEngine.Quaternion)
				b8 : \uE02F (type: UnityEngine.Quaternion[])
				c0 : \uE030 (type: UnityEngine.Transform[])
				c8 : \uE031 (type: UnityEngine.Transform[])
				d0 : \uE032 (type: UnityEngine.Transform[])
				d8 : \uE033 (type: UnityEngine.Transform)
				e0 : \uE034 (type: UnityEngine.Transform)
				e8 : \uE035 (type: UnityEngine.Transform)
				f0 : \uE036 (type: TwistRelax[])
				f8 : \uE037 (type: RootMotion.FinalIK.LimbIK[])
				100 : \uE038 (type: UnityEngine.GameObject)
				108 : \uE039 (type: System.Action)
				110 : \uE03A (type: PreviewMaterialSetter)
				118 : \uE03B (type: EFT.Interactive.BeaconPlacer)
				120 : \uE03C (type: FirearmsEffects)
				128 : \uE03D (type: FirearmsEffects)
				130 : \uE03E (type: CompassArrow)
				138 : \uE03F (type: UnityEngine.Transform[])
				140 : \uE040 (type: UnityEngine.Transform[])
				148 : \uE041 (type: System.Collections.Generic.List<>)
				150 : PointOfViewChanged (type: \uE9BF)
				158 : AuthorityBlender (type: EFT.Player.ValueBlender)
				160 : GrounderBlender (type: EFT.Player.ValueBlender)
				660 : \uE042 (type: System.Single)
				664 : \uE043 (type: System.Single)
				668 : _isDeadAlready (type: System.Boolean)
				669 : \uE044 (type: System.Boolean)
				168 : \uE045 (type: ObjectInHandsAnimator)
				170 : \uE046 (type: UnityEngine.GameObject)
				178 : \uE047 (type: System.Action)
				180 : \uE048 (type: System.Action<,EBodyPart,System.Single>)
				66c : \uE049 (type: UnityEngine.Vector3)
				678 : \uE04A (type: UnityEngine.Quaternion)
				188 : \uE04B (type: UnityEngine.GameObject)
				190 : \uE04C (type: EFT.Animations.ProceduralWeaponAnimation)
				688 : \uE04D (type: System.Boolean)
				198 : \uE04E (type: EFT.Player.)
				1a0 : DebugText (type: UnityEngine.UI.Text)
				68c : CurrentSurface (type: BaseBallistic.ESurfaceSound)
				690 : \uE052 (type: EFT.EnvironmentEffect.EnvironmentType)
				694 : HeavyBreath (type: System.Boolean)
				698 : VerticalSoundFactor (type: System.Single)
				69c : Muffled (type: System.Boolean)
				6a0 : \uE053 (type: UnityEngine.RaycastHit)
				6cc : \uE054 (type: System.Boolean)
				1a8 : NestedStepSoundSource (type: BetterSource)
				1b0 : _speechSource (type: BetterSource)
				6cd : OcclusionDirty (type: System.Boolean)
				6ce : DistanceDirty (type: System.Boolean)
				1b8 : FractureSound (type: UnityEngine.AudioClip)
				1c0 : PropIn (type: BaseSoundPlayer.SoundElement)
				1c8 : PropOut (type: BaseSoundPlayer.SoundElement)
				6cf : PreviousFaceShield (type: System.Boolean)
				6d0 : SpeechLocalPosition (type: UnityEngine.Vector3)
				1d0 : FaceshieldOn (type: UnityEngine.AudioClip)
				1d8 : FaceshieldOff (type: UnityEngine.AudioClip)
				1e0 : \uE055 (type: UnityEngine.AudioClip)
				6dc : \uE056 (type: UnityEngine.LayerMask)
				1e8 : \uE057 (type: System.Collections.Generic.Dictionary<BaseBallistic.ESurfaceSound,EFT.SurfaceSet>)
				1f0 : \uE058 (type: EFT.SurfaceSet)
				1f8 : \uE059 (type: EFT.SoundBank)
				200 : \uE05A (type: EFT.SoundBank)
				208 : \uE05B (type: UnityEngine.Coroutine)
				210 : \uE05C (type: UnityEngine.Coroutine)
				218 : \uE05D (type: UnityEngine.Coroutine)
				220 : \uE05E (type: UnityEngine.Coroutine)
				228 : \uE05F (type: UnityEngine.Coroutine)
				230 : \uE060 (type: UnityEngine.Coroutine)
				6e0 : \uE061 (type: System.Boolean)
				6e4 : \uE062 (type: System.Single)
				238 : \uE063 (type: BetterSource)
				6e8 : \uE064 (type: System.Single)
				240 : \uE065 (type: UnityEngine.AudioClip)
				6ec : \uE068 (type: System.Single)
				6f0 : \uE069 (type: System.Single)
				248 : \uE06A (type: System.Collections.Generic.List<EFT.Interactive.BetterPropagationVolume>)
				250 : \uE06B (type: System.Collections.Generic.List<EFT.Interactive.BetterPropagationVolume>)
				258 : \uE06C (type: EFT.Interactive.BetterPropagationVolume)
				6f4 : \uE06D (type: System.Boolean)
				260 : \uE06E (type: System.Action)
				6f8 : \uE06F (type: System.Single)
				6fc : \uE070 (type: System.Single)
				700 : \uE071 (type: System.Single)
				704 : \uE072 (type: System.Single)
				708 : \uE073 (type: System.Single)
				70c : \uE074 (type: System.Single)
				710 : \uE075 (type: System.Single)
				714 : \uE076 (type: System.Single)
				718 : \uE077 (type: System.Single)
				71c : \uE078 (type: System.Single)
				720 : \uE079 (type: System.Single)
				724 : \uE07A (type: System.Boolean)
				268 : POM (type: PlayerOverlapManager)
				270 : TriggerZones (type: System.Collections.Generic.List<System.String>)
				278 : OnExitTriggerVisited (type: \uE9BF)
				280 : InteractingWithExfiltrationPoint (type: \uE9CA)
				728 : LastDamageType (type: EFT.EDamageType)
				72c : LastDamagedBodyPart (type: EBodyPart)
				730 : PlacingBeacon (type: System.Boolean)
				731 : Destroyed (type: System.Boolean)
				288 : _animators (type: \uE1B4)
				290 : Speaker (type: \uE54A)
				298 : \uE07D (type: \uE4EF)
				2a0 : \uE07E (type: \uE4F0)
				2a8 : Spirit (type: EFT.PlayerSpirit)
				734 : EnabledAnimators (type: EFT.Player.EAnimatorMask)
				2b0 : Logger (type: EFT.Player.PlayerLogger)
				2b8 : Corpse (type: EFT.Interactive.Corpse)
				2c0 : LastAggressor (type: EFT.Player)
				2c8 : LastDamageInfo (type: \uE8EF)
				738 : LastBodyPart (type: EBodyPart)
				73c : _corpseAppliedForce (type: System.Single)
				378 : GetSensitivity (type: System.Func<System.Single>)
				380 : GetAimingSensitivity (type: System.Func<System.Single>)
				388 : _openAction (type: System.Action<System.Action>)
				740 : \uE07F (type: System.Single)
				744 : \uE080 (type: System.Single)
				748 : \uE081 (type: System.Int32)
				74c : \uE082 (type: System.Boolean)
				74d : \uE083 (type: System.Boolean)
				74e : \uE084 (type: System.Boolean)
				390 : \uE085 (type: \uE6B7)
				398 : \uE086 (type: UnityEngine.Renderer[])
				3a0 : \uE087 (type: UnityEngine.Camera)
				3a8 : \uE088 (type: UnityEngine.Coroutine)
				3b0 : \uE089 (type: UnityEngine.Coroutine)
				3b8 : \uE08A (type: \uE9CA)
				74f : \uE08B (type: System.Boolean)
				3c0 : \uE08C (type: UnityEngine.Animator)
				3c8 : \uE08D (type: UnityEngine.RuntimeAnimatorController)
				3d0 : \uE08E (type: System.Action<System.Boolean>)
				3d8 : \uE08F (type: System.Action)
				3e0 : \uE090 (type: System.Action<EPhraseTrigger,System.Int32>)
				3e8 : \uE091 (type: System.Action<System.Boolean>)
				3f0 : \uE092 (type: GenericEventTranslator)
				3f8 : \uE093 (type: EFT.Player.<EFT.InventoryLogic.NightVisionComponent>)
				400 : \uE094 (type: EFT.Player.<EFT.InventoryLogic.ThermalVisionComponent>)
				408 : \uE095 (type: EFT.Player.<EFT.InventoryLogic.FaceShieldComponent>)
				410 : \uE096 (type: System.String)
				418 : \uE097 (type: EFT.Game.Spawning.ISpawnPoint)
				750 : \uE098 (type: System.Single)
				420 : \uE099 (type: EFT.Interactive.InteractableObject)
				754 : \uE09A (type: System.Boolean)
				428 : \uE09B (type: EFT.Player)
				430 : \uE09C (type: EFT.Interactive.PlaceItemTrigger)
				438 : \uE09D (type: EFT.Interactive.ExfiltrationPoint)
				755 : \uE09E (type: System.Boolean)
				758 : \uE09F (type: System.Int32)
				440 : \uE0A0 (type: EFT.Profile)
				448 : \uE0A1 (type: \uE53D)
				450 : Physical (type: \uE20C)
				458 : \uE0A2 (type: System.Action<System.String,System.Int32>)
				75c : _updateQueue (type: EFT.EUpdateQueue)
				760 : _armsUpdateQueue (type: EFT.EUpdateQueue)
				764 : _armsUpdateMode (type: EFT.Player.EUpdateMode)
				768 : _bodyUpdateMode (type: EFT.Player.EUpdateMode)
				460 : \uE0A3 (type: \uE16D)
				468 : \uE0A4 (type: System.Collections.Generic.Dictionary<BodyPartType,>)
				470 : _healthController (type: \uE6E2)
				478 : _hitColliders (type: BodyPartCollider[])
				480 : _inventoryController (type: \uE7F6)
				488 : _handsController (type: EFT.Player.AbstractHandsController)
				490 : _questController (type: \uE664)
				498 : \uE0A5 (type: PlayerToGrassConnector)
				4a0 : \uE0A6 (type: System.Action<EFT.Player.AbstractHandsController,EFT.Player.AbstractHandsController>)
				4a8 : \uE0A7 (type: System.String)
				4b0 : Tracking (type: UnityEngine.Transform)
				76c : \uE0A8 (type: System.Single)
				770 : _armsupdated (type: System.Boolean)
				774 : _armsTime (type: System.Single)
				778 : _bodyupdated (type: System.Boolean)
				77c : _bodyTime (type: System.Single)
				780 : _nFixedFrames (type: System.Int32)
				784 : _fixedTime (type: System.Single)
				4b8 : \uE0AA (type: EFT.Player.)
				4c0 : \uE0AB (type: UnityEngine.WaitForFixedUpdate)
				788 : LastDeltaTime (type: System.Single)
				78c : _manuallyUpdated (type: System.Boolean)
				4c8 : _playerLookRaycastTransform (type: UnityEngine.Transform)
				78d : \uE0AC (type: EFT.Interactive.EDoorState)
				78e : \uE0AD (type: System.Boolean)
				78f : \uE0AE (type: System.Boolean)
				4d0 : PlayerBones (type: PlayerBones)
				4d8 : _preAllocatedArmorComponents (type: System.Collections.Generic.List<EFT.InventoryLogic.ArmorComponent>)
				4e0 : \uE0AF (type: System.Action<EFT.Interactive.ExfiltrationPoint,System.Boolean>)
				4e8 : \uE0B0 (type: \uE15B)
				790 : \uE0B1 (type: System.Boolean)
				791 : \uE0B2 (type: System.Boolean)
				4f0 : ExfilUnsubscribe (type: System.Action)
				4f8 : SessionEndUnsubscribe (type: System.Collections.Generic.List<System.Action>)
				792 : AggressorFound (type: System.Boolean)
				500 : \uE0B3 (type: System.Action)
				793 : \uE0B4 (type: System.Boolean)
				794 : \uE0B5 (type: EFT.Player.EProcessStatus)
				508 : \uE0B6 (type: EFT.Player.AbstractProcess)
				510 : \uE0B7 (type: EFT.InventoryLogic.Slot)
				518 : \uE0B8 (type: System.Action)
				520 : \uE0B9 (type: System.Action<>)
				528 : \uE0BA (type: EFT.InventoryLogic.EquipmentSlot[])
				530 : _removeFromHandsCallback (type: Comfort.Common.Callback)
				538 : \uE0BB (type: Comfort.Common.Callback)
				798 : \uE0BC (type: System.Single)
				79c : \uE0BD (type: System.Int32)
        */

        typedef std::unordered_map<Bones, games::c_vector3> t_bones;
		class c_player
		{
		public:
			UINT64					base = 0;
			c_player(UINT64 m)		{ base = m; };
			//
            t_bones                 bones;
			//
			games::c_vector3		get_pos();
			games::c_vector3		get_pos_root();
			games::c_vector3		get_pos_head();
            games::c_vector3        get_bone(Bones bone);
			games::c_vector3		get_fireport();
			bool					exists();
			bool					has_bone(int id);
            //
            UINT64                  get_profile();
            UINT64                  get_info();
            bool                    is_ai();
            //
            bool                    is_aiming();
            UINT64                  get_mp_camera();
			//
			bool					get_visible(Bones bone);
		};
	}
}